# Generated by Django 6.0.4 on 2026-04-30 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_place'),
        ('regions', '0002_initial'),
        ('tasks', '0004_alter_task_place'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Place',
        ),
    ]
