# Generated by Django 6.0.4 on 2026-05-17 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_place'),
        ('projects', '0003_project_assigned_users_project_project_manager'),
    ]

    operations = [
    ]
