# Generated by Django 5.2.13 on 2026-04-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'חדשה'), ('in_progress', 'בטיפול'), ('waiting_approval', 'ממתינה לאישור'), ('completed', 'הושלמה'), ('cancelled', 'מבוטלת')], default='new', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'נמוכה'), ('medium', 'בינונית'), ('high', 'גבוהה')], default='medium', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('drive_link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
