# Generated by Django 6.0.4 on 2026-04-30 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
        ('tasks', '0003_projecttask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='places.place'),
        ),
    ]
