# Generated by Django 6.0.4 on 2026-05-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_projecttask_project_alter_task_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='content_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='content_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='is_content_task',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='task_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='content_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='content_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='is_content_task',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
