# Generated by Django 5.2.13 on 2026-04-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('content_type', models.CharField(choices=[('image', 'תמונה'), ('video', 'וידאו'), ('text', 'טקסט'), ('link', 'קישור')], max_length=20)),
                ('file_url', models.URLField(blank=True)),
                ('drive_link', models.URLField(blank=True)),
                ('approval_status', models.CharField(choices=[('draft', 'טיוטה'), ('in_review', 'בסקירה'), ('approved', 'מאושר להפצה'), ('rejected', 'נדחה'), ('published', 'פורסם')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
