# Generated by Django 6.0.4 on 2026-05-18 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_items', '0002_initial'),
        ('tasks', '0006_projecttask_content_created_projecttask_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentitem',
            name='drive_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to='tasks.task'),
        ),
    ]
