# Generated by Django 6.0.4 on 2026-05-26 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_items', '0003_alter_contentitem_drive_link_and_more'),
        ('places', '0002_alter_place_address_alter_place_place_type_and_more'),
        ('projects', '0004_merge_20260517_1409'),
        ('regions', '0003_delete_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='associated_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to='projects.project'),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to='places.place'),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to='regions.region'),
        ),
    ]
